<a href="https://colab.research.google.com/github/tokyo8182/TensorFlow/blob/main/Colab_2_TensorFlow_2_0_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TensorFlow 1.X




### Installing TensorFlow 1.X



In [10]:
import tensorflow as tf

In [3]:
tf.__version__

'2.12.0'

### Constants

#### Defining a constant

In [6]:
# Defining a TensorFlow constant
tensor = tf.constant([[40, 8], [50, 7]])

In [17]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40,  8],
       [50,  7]], dtype=int32)>

In [8]:
# If a session is not initialized, we cannot access the values of the constant
tensor.eval()

NotImplementedError: ignored

#### Getting the values of a constant

In [15]:
session = tf.compat.v1.Session()

In [18]:
tf.compat.v1.global_variables_initializer()

In [11]:
session = tf.Session()

AttributeError: ignored

In [16]:
session.run(tf.compat.v1.global_variables_initializer())

RuntimeError: ignored

In [19]:
tensor_value = session.run(tensor)

RuntimeError: ignored

In [ ]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

### Variables

#### Defining a variable

In [20]:
# Defining a TensorFlow variable
variable = tf.Variable([[30, 20], [10, 45]])

In [21]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[30, 20],
       [10, 45]], dtype=int32)>

In [ ]:
# If a session is not initialized, we cannot access the values of the variable
variable.eval()

ValueError: ignored

#### Getting the values of a variable

In [ ]:
# Initializing a session
session = tf.Session()

In [ ]:
# Initializing ALL the variables from the session
session.run(tf.global_variables_initializer())

In [ ]:
# Running the eval method on the environment with the initialized session to retrieve values from it
variable.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

## TensorFlow 2.0

### Installing TensorFlow 2.0

In [22]:
!pip install tensorflow-gpu==2.0.0-alpha0

ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==2.0.0-alpha0 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.12.0)
ERROR: No matching distribution found for tensorflow-gpu==2.0.0-alpha0


In [23]:
import tensorflow as tf
import numpy as np

In [24]:
tf.__version__

'2.12.0'

### Constants

#### Defining a constant

In [27]:
# Defining a constant in TensorFlow 2.0
tensor_20 = tf.constant([[30, 20], [10, 45]])

In [28]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 20],
       [10, 45]], dtype=int32)>

In [29]:
# Getting the shape of a tensor
tensor_20.shape

TensorShape([2, 2])

#### Getting the values of a constant

In [30]:
# Getting the values straight from a TensorFlow constant with numpy, and without the need of a session
tensor_20.numpy()

array([[30, 20],
       [10, 45]], dtype=int32)

In [32]:
# We are able to convert a numpy array back to a TensorFlow tensor as well
numpy_tensor = np.array([[30, 20], [10, 45]])

In [33]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [34]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[30, 20],
       [10, 45]])>

### Variables

#### Defining a variable

In [35]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Getting the values of a variable

In [36]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Changing a specific value in the variable

In [37]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [38]:
tf2_variable[1, 1].assign(50)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,  50.,   6.]], dtype=float32)>

In [39]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,  50.,   6.]], dtype=float32)>

### Operations with tensors

In [40]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Addition between a scalar and a tensor

In [41]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [43]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Multiplication between a scalar and a tensor

In [44]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Using Numpy functions on TensorFlow tensors

In [45]:
# Getting the squares of all numbers in a TensorFlow tensor object
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [46]:
# Getting the square root of all numbers in a tensorflow tensor object
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Dot product between two tensors

In [51]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 20],
       [10, 45]], dtype=int32)>

In [52]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [47]:
 np.dot(tensor, tensor_20)

array([[ 50, 110],
       [130, 240]], dtype=int32)

### Strings in TensorFlow 2.0

In [53]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

#### Simple string operations

In [54]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [55]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

#### Storing arrays of strings

In [60]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI","5","8"])

In [61]:
# Iterating through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
tf.Tensor(b'5', shape=(), dtype=string)
tf.Tensor(b'8', shape=(), dtype=string)
